module.exports = {
  env: {
    MAINCHAIN_RPC_URL: process.env.MAINCHAIN_RPC_URL,
    MAINCHAIN_CHAIN_ID: process.env.MAINCHAIN_CHAIN_ID,
    MAINCHAIN_EXPLORER: process.env.MAINCHAIN_EXPLORER,
    ETH_EXPLORER: process.env.ETH_EXPLORER,
    ETH_NETWORK_NAME: process.env.ETH_NETWORK_NAME,
    ETH_NETWORK_ID: process.env.ETH_NETWORK_ID,
    XFUND_CONTRACT_ADDRESS: process.env.XFUND_CONTRACT_ADDRESS,
    XFUND_ABI: process.env.XFUND_ABI,
    XFUND_CONTRACT_SALT: process.env.XFUND_CONTRACT_SALT,
  },
}
